language: ruby
rvm:
  - 2.6.6
env:
  - TRAVIS_NODE_VERSION="10.16.2"
services:
  - postgresql
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - psql -c 'create database school_test;' -U postgres
  - RAILS_ENV=test bundle exec rails webpacker:compile
